### PR TITLE
fix: compatible with Obsidian 1.2.0 version

### PR DESCRIPTION
**Pull request by bytemain**
This close: #163 

It seem that Obisidian changed its property name.

### CODE REVIEW

**Comment by FlorianWoelki** [comment]
At the moment, I cannot merge or review this PR because I don't have access to the insider build. I'll leave this one open for now.

**Comment by Lisandra-dev** [comment]
Seems inheritance broken : 
image

**Comment by FlorianWoelki** [comment]
@Lisandra-dev I'll fix all the issues when obsidian `1.2.0` is officially released.

**Comment by Lisandra-dev** [comment]
I will wait 👍

**Comment by bytemain** [comment]
> Seems inheritance broken : image
> 
> More over, many icons jump, be disabled, returns to inheritance...

How to reproduce?

**Comment by bytemain** [comment]
Ah ha, But I meet another inheritance problem:

CleanShot 2023-03-31 at 19 08 25@2x

**Comment by Lisandra-dev** [comment]
Seems rules not working : 
image

(I have a rule for all .md files)

**Comment by bytemain** [comment]
> Seems rules not working : image image
> 
> (I have a rule for all .md files)
> 
> For reference, there is the result of `node` and `titleNode` when rules are applied : image

Fixed

**Comment by Lisandra-dev** [comment]
Now, I have the bug with rules > custom set icons instead of the other.

**Comment by bytemain** [comment]
Sure, Do it if you want.

**Pull request merged**
