### PR TITLE
remove "remove icon" if no icon is set

### PR DESCRIPTION
**Pull request by Mara-Li**
Little pull request to add this.

### CODE REVIEW

**Comment by FlorianWoelki** [comment]
Thank you for your PR!

Can you please revert the version change to `1.0.22`? I will add this PR to the next upcoming version with more features!

**Comment by Mara-Li** [comment]
It's done !

**Comment by FlorianWoelki** [comment]
Thanks! Can you also format the code. I will add prettier/eslint later. So your added lines line up with the rest?

**Comment by Mara-Li** [comment]
It is good, now ?

**Comment by FlorianWoelki** [comment]
Yes thank you!

**Pull request merged**
